spring:
  datasource:
    url: jdbc:mysql://database-3.ctap86niaksk.ap-south-1.rds.amazonaws.com/userDB?createDatabaseIfNotExist=true
    username: admin
    password: password
    hikari:
      initialization-fail-timeout: 0
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update