spring:
  datasource:
    url: jdbc:mysql://database-1.ctap86niaksk.ap-south-1.rds.amazonaws.com/userDB?createDatabaseIfNotExist=true
    username: root
    password: rootroot
    hikari:
      initialization-fail-timeout: 0
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      
server:
  port: 8090
